pipeline {
    agent {
        docker {
            image 'node:12-alpine' 
            args '-p 3000:3000' 
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'cd expensify && npm install' 
            }
        }
        stage('Test') {
            steps {
                sh 'cd expensify && npm run test'
            }
        }
    }
}